// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztrmokiqwxzindrhjcbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cm1va2lxd3h6aW5kcmhqY2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTUyODcsImV4cCI6MjA3MzYzMTI4N30.P0ObRY7pXrPI-R6R3Uosvaxt_cwUFDVwrzP6BXFiFRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});